//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketLine
    {
        public int BasketLines_ID { get; set; }
        public string BasketID { get; set; }
        public int Oppor_Id { get; set; }
        public int Quantity { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual tbl_Opportunity tbl_Opportunity { get; set; }
    }
}
