//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPPOR_HAS_VOLUN
    {
        public int OpporVolun_ID { get; set; }
        public int Oppor_Id { get; set; }
        public int Volun_Id { get; set; }
    
        public virtual tbl_Opportunity tbl_Opportunity { get; set; }
        public virtual tbl_Volunteer tbl_Volunteer { get; set; }
    }
}
