//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj_BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Volunteer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Volunteer()
        {
            this.OPPOR_HAS_VOLUN = new HashSet<OPPOR_HAS_VOLUN>();
        }
    
        public int Volun_Id { get; set; }
        public string VolunFname { get; set; }
        public string VolunLname { get; set; }
        public string VolunEmail { get; set; }
        public System.DateTime VolunDateofbirth { get; set; }
        public string VolunStreetaddress { get; set; }
        public string VolunStreetaddress2 { get; set; }
        public string VolunCity { get; set; }
        public string VolunState { get; set; }
        public string VolunZip { get; set; }
        public string County { get; set; }
        public Nullable<bool> VolunAvailableMonday { get; set; }
        public Nullable<bool> VolunAvailableMondayMorning { get; set; }
        public Nullable<bool> VolunAvailableMondayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableMondayEvening { get; set; }
        public Nullable<bool> VolunAvailableTuesday { get; set; }
        public Nullable<bool> VolunAvailableTuesdayMorning { get; set; }
        public Nullable<bool> VolunAvailableTuesdayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableTuesdayEvening { get; set; }
        public Nullable<bool> VolunAvailableWednesday { get; set; }
        public Nullable<bool> VolunAvailableWednesdayMorning { get; set; }
        public Nullable<bool> VolunAvailableWednesdayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableWednesdayEvening { get; set; }
        public Nullable<bool> VolunAvailableThursday { get; set; }
        public Nullable<bool> VolunAvailableThursdayMorning { get; set; }
        public Nullable<bool> VolunAvailableThursdayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableThursdayEvening { get; set; }
        public Nullable<bool> VolunAvailableFriday { get; set; }
        public Nullable<bool> VolunAvailableFridayMorning { get; set; }
        public Nullable<bool> VolunAvailableFridayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableFridayEvening { get; set; }
        public Nullable<bool> VolunAvailableSaturday { get; set; }
        public Nullable<bool> VolunAvailableSaturdayMorning { get; set; }
        public Nullable<bool> VolunAvailableSaturdayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableSaturdayEvening { get; set; }
        public Nullable<bool> VolunAvailableSunday { get; set; }
        public Nullable<bool> VolunAvailableSundayMorning { get; set; }
        public Nullable<bool> VolunAvailableSundayAfternoon { get; set; }
        public Nullable<bool> VolunAvailableSundayEvening { get; set; }
        public Nullable<bool> VoluntNutrition { get; set; }
        public Nullable<bool> VolunTrainingFacilitator { get; set; }
        public Nullable<bool> VolunAdmin { get; set; }
        public Nullable<bool> VolunGeneral { get; set; }
        public Nullable<bool> VolunHealthyliving { get; set; }
        public Nullable<bool> VolunDiseaseManagement { get; set; }
        public Nullable<bool> VolunFallsPrevention { get; set; }
        public Nullable<bool> VolunCaregiver { get; set; }
        public Nullable<bool> VolunMentalWellness { get; set; }
        public Nullable<bool> VolunEvents { get; set; }
        public Nullable<bool> VolunSocialMedia { get; set; }
        public string VolunOtherInterest { get; set; }
        public Nullable<bool> VolunBackgroundCheckRequired { get; set; }
        public Nullable<System.DateTime> VolunBackgroundCheckCompletedOn { get; set; }
        public Nullable<System.DateTime> VolunBackgroundCheckExpiresOn { get; set; }
        public string VolunActivitiesParticipated { get; set; }
        public Nullable<bool> VolunMarkVolunteer { get; set; }
        public Nullable<bool> VolunFlagged { get; set; }
        public string VolunFlaggedInformation { get; set; }
        public string VolunGeneralNotes { get; set; }
        public Nullable<decimal> VolunUpdateHours { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OPPOR_HAS_VOLUN> OPPOR_HAS_VOLUN { get; set; }
    }
}
